version: "3.7"
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.dockerfile
        volumes:
            - ./:/app
        depends_on:
            - db
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.dockerfile
        volumes:
            - ./:/app
    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.dockerfile
        volumes:
            - ./:/app
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5433:5432"
    node:
        image: node:14.6-alpine
        volumes:
            - ./:/app
        working_dir: /app
    mailer:
        image: mailhog/mailhog
        ports:
            - "8020:8025"
